included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
- Schwifty-Networking

whitelist_rules:

excluded: #paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods

disabled_rules: #rule identifiers to exclude from running
- line_length
- file_length
- closure_parameter_position
- variable_name
- type_name

# binary rules can set their severity level
force_cast: warning # implicitly
